"""add recipes pantry tables

Revision ID: 5872818b63af
Revises: 5e05d510eac8
Create Date: 2026-05-05 21:00:24.109923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5872818b63af'
down_revision: Union[str, Sequence[str], None] = '5e05d510eac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('cost_currency', sa.Text(), server_default='CHF', nullable=False),
    sa.Column('nutrition_ref', sa.Text(), nullable=True),
    sa.Column('default_role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_of_id', sa.UUID(), nullable=True),
    sa.Column('parent_recipe_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('yields', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('serving_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_time_min', sa.Integer(), nullable=True),
    sa.Column('active_time_min', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('hero_photo_key', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_dough_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['version_of_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pantry_item_id', sa.UUID(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantry_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('pantry_item_id', sa.UUID(), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('group_label', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('grams', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit_display', sa.Text(), nullable=True),
    sa.Column('unit_display_qty', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('leaven_flour_pct', sa.Numeric(precision=5, scale=2), server_default='50', nullable=False),
    sa.Column('cost_override_per_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('nutrition_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantry_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('min_seconds', sa.Integer(), nullable=True),
    sa.Column('max_seconds', sa.Integer(), nullable=True),
    sa.Column('target_temp_c', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_kind', sa.Text(), nullable=True),
    sa.Column('ingredient_ids', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('parallelizable_with', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_steps')
    op.drop_table('recipe_ingredients')
    op.drop_table('pantry_price_history')
    op.drop_table('recipes')
    op.drop_table('pantry_items')
    # ### end Alembic commands ###
