"""add starters feedings

Revision ID: 850039769bd4
Revises: cbca103e508c
Create Date: 2026-05-05 22:39:18.072065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850039769bd4'
down_revision: Union[str, Sequence[str], None] = 'cbca103e508c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hydration_pct', sa.Numeric(precision=5, scale=1), server_default='100', nullable=False),
    sa.Column('peak_base_hours', sa.Numeric(precision=4, scale=1), server_default='6', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starter_feedings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('starter_id', sa.UUID(), nullable=False),
    sa.Column('fed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ratio', sa.Text(), nullable=True),
    sa.Column('flour_mix', sa.Text(), nullable=True),
    sa.Column('kitchen_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('peak_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['starter_id'], ['starters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starter_feedings')
    op.drop_table('starters')
    # ### end Alembic commands ###
