"""add bakes photos tweaks

Revision ID: cbca103e508c
Revises: 5872818b63af
Create Date: 2026-05-05 22:13:02.861895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbca103e508c'
down_revision: Union[str, Sequence[str], None] = '5872818b63af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('scale_multiplier', sa.Numeric(precision=6, scale=3), server_default='1', nullable=False),
    sa.Column('kitchen_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('kitchen_humidity', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('flour_brand', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('start_weight_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('final_weight_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rise_height_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('internal_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('crumb_score', sa.Integer(), nullable=True),
    sa.Column('crust_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bake_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bake_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('step_ord', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bake_id'], ['bakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bake_tweaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bake_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('apply_next_time', sa.Boolean(), nullable=False),
    sa.Column('resolved_in_recipe_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bake_id'], ['bakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['recipe_ingredients.id'], ),
    sa.ForeignKeyConstraint(['resolved_in_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['recipe_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bake_tweaks')
    op.drop_table('bake_photos')
    op.drop_table('bakes')
    # ### end Alembic commands ###
